export default function privacyPolicy() {
    return(
        <div className="w-full items-center justify-center flex px-6" >
            <div className="max-w-[580px]">
                <h1 className="text-carbon-800 text-[40px] sm:text-5xl leading-none tracking-[-0.4px] pb-2">Políticas de privacidade</h1>
                <h3 className="text-carbon-400 text-[22px] sm:text-2xl/[32px]">Atualizado em 6 de dezembro de 2025</h3>

                <div className="mt-10 text-xl/[29.2px] text-carbon-800 gap-[29.2px] flex-col flex">
                    <p>A presente Política de Privacidade descreve como o site www.palaga.com.br, mantido pela Interception Digital LTDA (CNPJ 49.821.411/0001-37), com sede em Rio Grande/RS, coleta, utiliza e protege os dados pessoais dos usuários. Ao acessar ou utilizar este site, o usuário declara estar ciente e de acordo com as práticas descritas neste documento.</p>
                    <p>Este site tem como objetivo a divulgação de conteúdos sobre organização pessoal e a apresentação de produtos digitais oferecidos pela marca Pálaga. Para fornecer a melhor experiência possível, utilizamos ferramentas que coletam dados de navegação, como cookies, identificadores de dispositivo e informações sobre interação com páginas e conteúdos. Esses dados podem ser utilizados para fins estatísticos, otimização de navegação, personalização de anúncios e medição de desempenho de campanhas. Entre os dados coletados automaticamente estão endereço IP, tipo de navegador, páginas visitadas, tempo de permanência e outros elementos técnicos comumente utilizados por plataformas de analytics e publicidade.</p>
                    <p>Eventualmente, podemos solicitar informações fornecidas diretamente pelo usuário, como nome e e-mail, especialmente em formulários de newsletter, pesquisas de opinião ou materiais específicos. O fornecimento desses dados é voluntário e ocorre mediante consentimento do usuário no momento do envio do formulário correspondente. Os dados pessoais fornecidos são utilizados exclusivamente para os fins informados no ato da coleta, como envio de conteúdos, newsletters, contato ou participação em pesquisas. Quando o usuário se inscreve para receber comunicações, seu endereço de e-mail passa a integrar nossa lista de envio, da qual ele pode se descadastrar a qualquer momento.</p>
                    <p>Também utilizamos ferramentas de publicidade e monitoramento, como pixels e tags de plataformas de anúncios, incluindo Google Ads, Meta Ads e Pinterest Ads, entre outras que possam ser implementadas futuramente. Essas ferramentas auxiliam na análise de comportamento, segmentação e otimização de campanhas de marketing. Embora adotemos práticas para garantir o uso responsável dessas tecnologias, cada plataforma possui suas próprias políticas de privacidade, sendo responsabilidade do usuário consultá-las quando desejar compreender em maior profundidade como seus dados podem ser tratados por terceiros.</p>
                    <p>Toda a infraestrutura técnica do site é hospedada em serviços de terceiros, como plataformas de deploy e hospedagem (por exemplo, Vercel), além do provedor de domínio Registro.br. Essas empresas podem tratar dados técnicos de navegação com finalidades de funcionamento, segurança e monitoramento de desempenho. Embora parceiros externos possam atuar no tratamento de dados, não compartilhamos informações pessoais identificáveis fora das hipóteses estritamente necessárias para o funcionamento do site ou mediante consentimento do usuário.</p>
                    <p>Os dados pessoais são armazenados pelo tempo necessário para cumprir com as finalidades específicas para as quais foram coletados, respeitando princípios de necessidade, adequação e segurança. Adotamos medidas técnicas e administrativas razoáveis para proteger os dados contra acessos não autorizados, perdas, destruição ou alterações indevidas. No entanto, por se tratar de ambiente digital, nenhum sistema é completamente imune a riscos, e o usuário reconhece essa possibilidade ao utilizar o site.</p>
                    <p>O titular dos dados pode, a qualquer momento, solicitar informações sobre o uso de seus dados pessoais, atualizar informações, pedir exclusão, retirar consentimento ou esclarecer dúvidas relacionadas ao tratamento. Para isso, disponibilizamos o e-mail de contato oficial contato@palaga.com.br, por meio do qual responderemos às solicitações com base na legislação aplicável.</p>
                    <p>Esta Política de Privacidade poderá ser alterada a qualquer momento, sempre que necessário para refletir mudanças no site, em práticas de tratamento de dados ou em exigências legais. Recomendamos que o usuário consulte este documento periodicamente. O uso continuado do site após eventuais alterações será interpretado como concordância com os termos atualizados.</p>
                </div>
            </div>
        </div>
 )
 } 