export default function TermsOfUse() {
    return(
        <div className="w-full items-center justify-center flex px-6" >
            <div className="max-w-[580px]">
                <h1 className="text-carbon-800 text-[40px] sm:text-5xl leading-none tracking-[-0.4px] pb-2">Termos de uso</h1>
                <h3 className="text-carbon-400 text-[22px] sm:text-2xl/[32px]">Atualizado em 6 de dezembro de 2025</h3>

                <div className="mt-10 text-xl/[29.2px] text-carbon-800 gap-[29.2px] flex-col flex">
                    <p>Os presentes Termos de Uso regulam o acesso e a utilização do site www.palaga.com.br, mantido pela Interception Digital LTDA. Ao navegar pelo site, o usuário concorda com as condições estabelecidas neste documento. Caso não concorde com algum dos termos, recomenda-se interromper o uso do site.</p>
                    <p>Este site tem finalidade informativa e comercial, apresentando conteúdos relacionados à organização pessoal e divulgação de produtos digitais da Pálaga. Todo o conteúdo publicado, incluindo textos, imagens, gráficos, vídeos, identidade visual, materiais de apoio e quaisquer outros elementos criativos, é protegido por direitos autorais e não pode ser reproduzido, distribuído, copiado ou utilizado para fins comerciais sem autorização expressa da Interception Digital LTDA. O uso indevido de qualquer material disponibilizado poderá resultar em responsabilização civil e/ou penal conforme a legislação vigente.</p>
                    <p>Os produtos digitais divulgados no site são comercializados exclusivamente por meio de plataformas externas, como a Hubla ou outras plataformas eventualmente utilizadas no futuro. O processo de compra, pagamento, entrega do produto e suporte pós-compra ocorre integralmente nessas plataformas, sendo elas responsáveis pelos procedimentos e políticas relacionadas às transações. As informações aqui disponibilizadas sobre produtos, preços, benefícios ou conteúdos podem ser alteradas a qualquer momento, sem aviso prévio, conforme a necessidade de atualização ou estratégia comercial.</p>
                    <p>O usuário compreende que o site pode utilizar cookies, pixels e tecnologias semelhantes para aprimorar a experiência de navegação, melhorar o desempenho, personalizar conteúdos e otimizar campanhas publicitárias. O uso contínuo do site caracteriza concordância com a utilização dessas tecnologias, conforme esclarecido em nossa Política de Privacidade.</p>
                    <p>Links externos podem ser disponibilizados em diversas áreas do site, incluindo páginas de produtos, artigos e materiais informativos. Esses links são fornecidos apenas como referência e conveniência. Não temos controle sobre o conteúdo de sites de terceiros e não nos responsabilizamos por informações, políticas, produtos ou serviços oferecidos fora do domínio palaga.com.br. O usuário é incentivado a verificar os termos e políticas dos sites acessados por meio de links externos.</p>
                    <p>Os conteúdos publicados no site têm finalidade exclusivamente informativa e educacional, não constituindo aconselhamento profissional de qualquer natureza, incluindo consultoria jurídica, financeira, médica ou psicológica. Cada usuário é responsável pela forma como interpreta e aplica as informações fornecidas, reconhecendo que resultados podem variar de acordo com sua realidade, contexto e dedicação individual.</p>
                    <p>Reservamo-nos o direito de modificar estes Termos de Uso a qualquer momento, sempre que houver necessidade de atualização do site, ajustes legais ou alteração nas estratégias de comunicação e comercialização. O uso contínuo do site após modificações representa aceitação dos novos termos.</p>
                    <p>Em caso de dúvidas sobre este documento ou sobre qualquer aspecto relacionado ao uso do site, o usuário pode entrar em contato pelo e-mail contato@palaga.com.br, onde prestaremos esclarecimentos dentro de prazo razoável.</p>
                </div>
            </div>
        </div>
 )
 } 